image:
  repository: ghcr.io/truegoric/k8s-insider
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

settings:
  kubernetes:
    serviceCidr: 10.96.0.0/12
    podCidr: 10.244.0.0/16
    clusterAddress: "192.168.49.2" # this should be set to the public IP of the cluster
  peerDns: "10.96.0.10"

imagePullSecrets: []
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - SYS_MODULE

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
