apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-insider.fullname" . }}
  labels:
    {{- include "k8s-insider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.type | eq "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}
      targetPort: vpn
      protocol: UDP
      name: vpn
  selector:
    {{- include "k8s-insider.selectorLabels" . | nindent 4 }}
