[package]
name = "k8s-insider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k8s-insider-core = { path = "../k8s-insider-core" }
kube = { workspace = true }
k8s-openapi = { workspace = true }
clap = { version = "4.3.2", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.18"
tokio = { workspace = true, features = ["rt"] }
anyhow = "1.0.71"
ipnet = "2.7.2"
