[package]
name = "k8s-insider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k8s-insider-core = { path = "../k8s-insider-core" }
kube = { version = "0.83.0", features = ["client", "rustls-tls", "kube-client", "ws"], default-features = false }
k8s-openapi = { version = "0.18.0", features = ["v1_21"] }
clap = { version = "4.3.2", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.18"
tokio = { version = "1.28.2", features = ["rt", "macros", "io-util"] }
anyhow = "1.0.71"
ipnet = "2.7.2"
