#!/command/with-contenv bash
# shellcheck shell=bash

WG_IF=wg0

NFT_TABLE=tun_table

echo '[tunnel] removing nftables...'
nft delete table inet $NFT_TABLE

echo "[tunnel] removing $WG_IF interface..."
ip link delete dev $WG_IF
