#!/command/with-contenv bash
# shellcheck shell=bash

NFT_TABLE=tun_table
ETH_IF=eth0

WG_IF=wg0
WG_SERVER_CONFIG_PATH=/config/wg0.conf
WG_MTU=$(ip link show $ETH_IF | awk -e '{for (i=1; i<=NF;i++){ if ($i == "mtu") {print $(i+1) - 80} }}')

echo '[tunnel] Setting up WireGuard...'

echo '[tunnel] wg link up...'
wg-quick up $WG_SERVER_CONFIG_PATH

ip link set mtu "$WG_MTU" dev $WG_IF

echo '[tunnel] setting up nftables...'
nft add table inet $NFT_TABLE
nft add chain inet $NFT_TABLE postrouting '{ type filter hook postrouting priority nat; }'
nft add chain inet $NFT_TABLE prerouting '{ type filter hook prerouting priority raw; }'
nft add chain inet $NFT_TABLE forward '{ type filter hook forward priority filter; }'

nft add rule inet $NFT_TABLE forward meta iif $WG_IF accept
nft add rule inet $NFT_TABLE forward meta oif $WG_IF accept
nft add rule inet $NFT_TABLE forward meta iif $ETH_IF accept
nft add rule inet $NFT_TABLE forward meta oif $ETH_IF accept

echo '[tunnel] limiting TCPMSS...'
nft add rule inet $NFT_TABLE prerouting tcp flags syn tcp option maxseg size set $((WG_MTU - 40)) # 20 bytes IP header + 20 bytes TCP header

echo '[tunnel] setting up nat for WireGuard interface...'
nft add rule inet $NFT_TABLE postrouting meta iif $WG_IF meta oif $ETH_IF masquerade

echo '[tunnel] Finished!'
